### ISSUE TITLE
when  painc in method,the http server will be  exit

### ISSUE THREAD

**Issue by zhuxiujia** [http-rs/tide#433]
when  painc in method,the http server will be  exit.

There is no way to intercept exceptions

**Comment by yoshuawuyts** [comment]
@zhuxiujia Hey, thanks for opening. That's accurate, when a panic occurs it indicates a programmer error and we exit the program. We currently don't have a model for graceful shutdown without risking resource starvation, and instead rely on a process manager to log the crash and reboot the process.

We've chosen this model because alternative models risked either deadlocking, or quietly losing resources until the server became unresponsive without crashing. Failing fast and early is not necessarily ideal, but we thought it was better than the alternatives.
