### ISSUE TITLE
Making tide::server private has broken testing

### ISSUE THREAD

**Issue by marhoily** [http-rs/tide#527]
It seems to me that making tide::server private broke the example of testing as shown in [realworld-tide](https://github.com/colinbankier/realworld-tide/graphs/contributors) repository. I can't call into_http_service() anymore. I'm very fresh to Rust and I probably am missing something. 

I come from the C# background and it seems to me that being testable is an essential feature of a web-framework. Could you give me an idea of how to test tide? I haven't found it in the examples folder in this repo. 

It would seem ideal if all the middle-ware\routing was testable in a synchronous manner without engaging any I\O or OS network stack. Is such a thing possible\planned with tide?

**Comment by yoshuawuyts** [comment]
@marhoily `tide::Server` implements the `HttpService` trait directly in `tide@0.8.0`. So there's no need to call `into_http_service` anymore since `tide::Server` already provides all it needs! In the next version (out today, if I can manage haha) we get rid of the trait entirely and expose `Server::respond` directly which replaces the use of the mock server. Example of the new API in use:

https://github.com/http-rs/tide/blob/9a143b3098c93ecc9f4ecd5d69d57a8a3244ecc6/tests/nested.rs#L74-L78

([commit that introduced it, replacing the old API](https://github.com/http-rs/tide/pull/503/files#diff-e18e54435df9f89db5c98a63e508b8efR116))

Hope this helps!

**Comment by marhoily** [comment]
Compiler still complains that the method Request::new is private. Am I missing something?

**Comment by marhoily** [comment]
Found it. I should have reference http-types 2.0.0 crate explicitly. God Rust messes up with my assumptions of possible!
