### ISSUE TITLE
Tide logging issue with nested routes — needs investigation

### ISSUE THREAD

**Issue by jbr** [http-rs/tide#551]

**Comment by eribol** [comment]
This is my nested route:
`app.at("/school").nest({
            use crate::school::school::{school, school_detail, timetable, teachers};
            let mut api = tide::with_state(state.clone());
            api.at("").all(school);
            api.at("/:school").all(school_detail);
            api.at("/:school/timetable").all(timetable);
            api.at("/:school/teachers").all(teachers);
            api
        });
`
and i am requesting to "school/720917/teachers" and logging is:

> {"level":30,"time":1590551990049,"msg":"<-- Request received","method":"GET","path":"/school/720917/teachers"}
{"level":30,"time":1590551990049,"msg":"<-- Request received","method":"GET","path":"/720917/teachers"}
bura7
bura1
bura5
{"level":30,"time":1590551990056,"msg":"--> Response sent","method":"GET","path":"/720917/teachers","status":200,"duration":"6.599095ms"}
{"level":30,"time":1590551990056,"msg":"--> Response sent","method":"GET","path":"/school/720917/teachers","status":200,"duration":"6.682995ms"}
>
but its saying that response of requesting to "/720917/teachers" is okey. And when i tried requesting same route log says:
>{"level":30,"time":1590552199144,"msg":"<-- Request received","method":"GET","path":"/720917/teachers"}
{"level":40,"time":1590552199144,"msg":"--> Response sent","method":"GET","path":"/720917/teachers","status":404,"duration":"10.105µs"}
>
Which its true because there is no route with "/720917/teachers". But logging says its okey. It should not requesting but if it was about requesting, it should response 404. 

Sorry for bad language, not native speaker here.

**Comment by yoshuawuyts** [comment]
Related: https://github.com/http-rs/tide/issues/396
