### ISSUE TITLE
Why is Server::middleware an Arc<Vec<Arc<>>>?

### ISSUE THREAD

**Issue by Fishrock123** [http-rs/tide#636]
https://github.com/http-rs/tide/blob/dc4f4ac2e2204cca0eb7f09a946212597da1924a/src/server.rs#L133

This seems like it could just be either an `Arc<Vec<>>` or a `Vec<Arc<>>`? What am I missing?

**Comment by jbr** [comment]
I'm not sure about this, and hope someone corrects me, but I think the alternative is for it to be an `Arc<Vec<Box<dyn Middleware<State>>>>` — the trait object isn't Sized, so it needs to be wrapped with some sort of smart pointer (box/arc/etc) to be put into a heterogeneous Vec. If it's boxed, it won't be individually Clone, which I assume is important somewhere else

**Comment by yoshuawuyts** [comment]
I don't remember why this is the case hah; I didn't write the middleware code. But what @jbr is saying matches my interpretation of this as well.

**Comment by tirr-c** [comment]
I remember `Vec<Arc<>>` was because each middleware needed to be individually cloneable when middleware interface was first designed. Back then, app nesting was implemented by manually walking through the router tree. Configured middleware was collected during the walk and concatenated in a single `Vec`; that's why `Arc<dyn Middleware>` was needed.

Maybe this is not relevant anymore; now we don't concatenate middleware chains. Feel free to change the type if all tests pass well.

**Comment by Fishrock123** [comment]
I ended up changing Surf's to also be `Arc<Vec<Arc<>>>` in https://github.com/http-rs/surf/pull/194/files#diff-31bbf71c54bca98a0ae3d40a327af940R32 ... I know the `Arc<Vec<>>` part was necessary but I'm not sure about the inner `Arc`s.
