### ISSUE TITLE
serve file API possibly broken?

### ISSUE THREAD

**Issue by ajstrand** [http-rs/tide#796]
I tried using the serve_file API in Tide 0.16, but when I copy the example in the examples directory(along with creating an example.html file to test with), I get the following error from tide's logger middleware.

```Rust
tide::log Logger started
    level Info
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

```

This my whole example program for reference:

```Rust
#[async_std::main]
async fn main() -> Result<(), std::io::Error> {
    tide::log::start();
    let mut app = tide::new();

    app.at("/").get(|_| async { Ok("Hello, world!") });
    app.at("/hello").serve_file("test.html")?;
    app.listen("127.0.0.1:4000").await?;
    Ok(())
}

```

The test.html file exists along side my main.rs file in the src folder. 

Im using macOS Catalina on an intel based Mac, if that helps at all.

**Comment by mendelt** [comment]
It looks like your program can't find `test.html` and that's probably because the working directory is not the 'src' dir when your program is running. My guess would be that you're starting the program from the root directory of your project. So you could move your `test.html` there or you could change `app.at("/hello").serve_file("test.html")?;` to `app.at("/hello").serve_file("src/test.html")?;`

If that still does not solve your problem you could try changing the path to `test.html` to a fully qualified path to get around the dependency on the working dir. I'll see if I can add a comment about this to the example.

**Comment by ajstrand** [comment]
@mendelt I used your second suggestion and that solved my problem. I was able to serve an HTML page just fine. 

If someone isn't using an absolute/fully qualified path, would it be helpful to add a note in the docs mentioning that path of the file is based on the current working directory when your server is run?

**Comment by mendelt** [comment]
Thank you! We're currently re-working this piece of functionality. Contributions are always welcome but maybe this is not the best thing to contribute on right now.
I'll see if I can get this cleared up in the next version we're working on. I think a better error message, for example one that tells you the complete path of the file it couldn't find would be more helpful too.
